#!/bin/bash

# Script to create a Pull Request for Recoll update
# Usage: ./create-pr.sh <version> <current_version> <branch_name>

set -e

VERSION="$1"
CURRENT_VERSION="$2"
BRANCH_NAME="$3"

if [ -z "$VERSION" ] || [ -z "$CURRENT_VERSION" ] || [ -z "$BRANCH_NAME" ]; then
    echo "Usage: $0 <version> <current_version> <branch_name>"
    exit 1
fi

echo "Creating Pull Request for Recoll update..."

# Create branch and commit changes
create_branch_and_commit() {
    echo "Creating branch: $BRANCH_NAME"
    git checkout -b "$BRANCH_NAME"
    
    echo "Adding changes..."
    git add Casks/recoll.rb
    
    echo "Committing changes..."
    git commit -m "Update Recoll to version $VERSION

- Updated version from $CURRENT_VERSION to $VERSION
- Updated SHA256 hash for verification

Automated update via GitHub Actions"
    
    echo "Pushing branch..."
    git push origin "$BRANCH_NAME"
}

# Create Pull Request using GitHub CLI
create_pull_request() {
    local pr_title="Update Recoll to version $VERSION"
    local pr_body="## Update Recoll to version $VERSION

This PR updates the Recoll cask to the latest version.

**Changes:**
- Updated version from \`$CURRENT_VERSION\` to \`$VERSION\`
- Updated SHA256 hash for verification

**Source:** [Recoll macOS Downloads](https://www.recoll.org/downloads/macos/)

This update was automatically generated by GitHub Actions."

    echo "Creating Pull Request..."
    gh pr create \
        --title "$pr_title" \
        --body "$pr_body" \
        --base master \
        --head "$BRANCH_NAME"
}

# Main execution
main() {
    create_branch_and_commit
    create_pull_request
    
    echo "✅ Pull Request created successfully!"
    echo "Branch: $BRANCH_NAME"
    echo "Version: $CURRENT_VERSION -> $VERSION"
}

main "$@"

