# CI workflow for Recoll Homebrew Cask
# Following Zen of Python: Simple, explicit, readable

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Test the Recoll cask installation and basic functionality
  test:
    name: Test Recoll Cask
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Link tap for testing
        run: |
          # Link the repository to Homebrew's tap directory
          ln -s "$GITHUB_WORKSPACE" "$(brew --prefix)/Library/Taps"

      - name: Verify cask syntax
        run: |
          # Validate cask file syntax
          brew audit --strict --online recoll

      - name: Install Recoll cask
        run: |
          # Test installation
          brew install --cask recoll --verbose

      - name: Verify installation
        run: |
          # Check that Recoll app was installed
          if [[ ! -d "/Applications/Recoll.app" ]]; then
            echo "Error: Recoll.app not found in /Applications/"
            exit 1
          fi
          
          # Verify app structure
          if [[ ! -x "/Applications/Recoll.app/Contents/MacOS/recoll" ]]; then
            echo "Error: Recoll executable not found or not executable"
            exit 1
          fi
          
          echo "Recoll installation verified successfully"

      - name: Test basic functionality
        run: |
          # Add Recoll to PATH for testing
          export PATH="/Applications/Recoll.app/Contents/MacOS:$PATH"
          
          # Test that recoll command is available
          if ! command -v recoll >/dev/null 2>&1; then
            echo "Error: recoll command not found in PATH"
            exit 1
          fi
          
          # Test basic help command
          recoll --help || echo "Help command completed"
          
          echo "Basic functionality test passed"

      - name: Clean up installation
        if: always()
        run: |
          # Clean up the installation to free up space
          brew uninstall --zap --force recoll || true
          
          # Remove any remaining files
          sudo rm -rf "/Applications/Recoll.app" || true
          rm -rf "$HOME/.recoll" || true
          rm -rf "$HOME/.config/Recoll.org" || true
          
          echo "Cleanup completed"
